[playwright]

#options chromium, firefox, webkit
browser = chromium

#Set false to run headed
headless = False

slow_mo = 500

Force_new_browser_session = True


#Skip test

base_url = http://localhost:3000/